### ISSUE TITLE
Adding a thank you page

### ISSUE THREAD

**Issue by natron19** [mel-quark/s.e.p.t.o#5]
URL is /thank_you 

* Ensure the link coming from /pledge redirects to thankyou_path on submit 
* The Layout of this page will include a large image (preferably entire page) of an octopus along with a centered div with the text below. 
* Ensure the user is presented with the following text: "Thank you for contributing to the safety of our treasured forest monster. We will be adding you to the "do not face-grab" list that the octopi use to ensure you are safe in our wonderful forests. In the meantime you will be sent copious amount of spam in the near future." 
* The page can be delivered via a ThankYou Controller with a #show action

**Comment by GGadow** [comment]
Since we will also have an About page not tied to a particular database model, would it be acceptable to have one controller for managing both pages?

**Comment by mel-quark** [comment]
@natron19 this is a wonderful ticket =)
@GGadow sure, we can use the same controllers. call it the `static_controller`

**Comment by jjs0sbw** [comment]
Alright... finishing up the details..

On Sat, Aug 15, 2015 at 10:07 PM, Nathan R <notifications@github.com> wrote:

> Closed #5 <https://github.com/mel-quark/s.e.p.t.o/issues/5>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mel-quark/s.e.p.t.o/issues/5#event-383467256>.
>



-- 
Joe Simpson
“Reasonable people adapt themselves to the world. Unreasonable people
attempt to adapt the world to themselves. All progress, therefore, depends
on unreasonable people.”
George Bernard Shaw
